### ISSUE TITLE
ntlm-proxy is not getting started

### ISSUE THREAD

**Issue by varunpradhan** [bjowes/cypress-ntlm-auth#97] opened 2020-01-23 11:00 UTC
Hi @bjowes ,

I have copied the code in another location and trying to run command `npm run cypress-ntlm` then the ntlm-proxy is not getting started. I am facing below error:

![image](https://user-images.githubusercontent.com/26091432/72979134-aad00080-3dfd-11ea-8b3d-8cddc7aa5919.png)

**Comment by bjowes** [comment] 2020-01-23 11:59
I think this is because you are running `npm run cypress-ntlm` from the `node_modules\.bin` folder. Try running it from the project root folder.

**Comment by varunpradhan** [comment] 2020-01-23 13:09
This was because I didn't copied `ca.private.key` and `ca.public.key`. Do we need to copy these too as I didn't copied `node_module and \.http-mitm-proxy\keys` folder?

As soon as I copied `\.http-mitm-proxy\keys` folder with the keys in it, it started working.

**Comment by bjowes** [comment] 2020-01-23 13:26
No, you shouldn't need to copy .http-mitm-proxy folder - it is created automatically when the proxy starts. Did you get it working?

**Comment by varunpradhan** [comment] 2020-01-23 13:31
Yes I did get it working after I copied the 2 keys

**Comment by bjowes** [comment] 2020-01-23 14:36
Ok, I'll try to reproduce what you did.

**Comment by varunpradhan** [comment] 2020-01-23 15:51
Ok Thank you @bjowes  👍 

Also just out of the box can I have a helping hand from you in few of my doubts related to cypress?
Thanks

**Comment by bjowes** [comment] 2020-01-23 21:22
I tried to reproduce this but didn't have any issues after copying my test project to a new folder. When copying and skipping node_modules, make sure you run `npm install` in the new folder to setup the node_modules content in the new folder. 

As for support, I mainly offer support for my plugin here. You can try me - if it is something I can answer without much effort I'll do it, otherwise I recommend the cypress docs (which are really good actually). I'll close the issue, but you can ask your question in this thread.

**Closed by bjowes** 2020-01-23 21:22 UTC

**Comment by varunpradhan** [comment] 2020-01-24 06:08
Hi @bjowes 

I am unable to use fixtures inside `When,And` etc. It is showing me an error : `TypeError: Cannot read property 'data' of undefined`

I have created a Test.feature file to test the fixture and below is the code :

Feature File:
![image](https://user-images.githubusercontent.com/26091432/73048012-b2df7d00-3e9d-11ea-8c13-e0d612095e20.png)

Step Definition File:
![image](https://user-images.githubusercontent.com/26091432/73048026-c38ff300-3e9d-11ea-8ce3-b09279b37f36.png)

Below is the test runner error snippet:
![image](https://user-images.githubusercontent.com/26091432/73048049-d6a2c300-3e9d-11ea-84e1-307e9ff1d8aa.png)

Can you please help me on this? How to resolve this?

**Comment by bjowes** [comment] 2020-01-24 07:49
Try this:
`cy.fixture('createTestData').as('data')`

**Comment by varunpradhan** [comment] 2020-01-24 09:12
This too didn't worked :(

**Comment by bjowes** [comment] 2020-01-24 11:06
I'm a bit unsure how it works when you are mixing before with cucumber steps. According to the docs it seems to be ok, but I would still try moving the fixture call into the Given block - that way you are certain that it is run with the Given statement.

**Comment by varunpradhan** [comment] 2020-01-24 13:07
I have moved the code to Given still the code is not working. Can you share how it is done by you in your project. Am I doing it in a right way?

**Comment by lgandecki** [comment] 2020-01-24 16:03
for a lost googler - here is a solution to this problem https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/317#issuecomment-578191635

**Comment by bjowes** [comment] 2020-01-24 18:54
Thanks @lgandecki - it seemed correct to me, good to know that you shouldn't import mocha. We didn't do that in our own project but I thought it wouldn't matter. @varunpradhan - is it working now?

**Comment by varunpradhan** [comment] 2020-01-24 19:04
Hi @bjowes Yes it is working now. Thank you :)
